// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExplanationText: typeof import('./src/components/ExplanationText.vue')['default']
    FlameIcon: typeof import('./src/components/icons/FlameIcon.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEl: typeof import('naive-ui')['NEl']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NMenu: typeof import('naive-ui')['NMenu']
    NModal: typeof import('naive-ui')['NModal']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PriceFormInput: typeof import('./src/components/PriceFormInput.vue')['default']
    RecommendationsModal: typeof import('./src/components/RecommendationsModal.vue')['default']
    ResultCharts: typeof import('./src/components/ResultCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextQuote: typeof import('./src/components/TextQuote.vue')['default']
    TheConsumptionParameters: typeof import('./src/components/TheConsumptionParameters.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheGasCalculator: typeof import('./src/components/TheGasCalculator.vue')['default']
    TheNavigation: typeof import('./src/components/TheNavigation.vue')['default']
    ThePriceParameters: typeof import('./src/components/ThePriceParameters.vue')['default']
    TheResult: typeof import('./src/components/TheResult.vue')['default']
  }
}
